### ISSUE TITLE
v3.0.0 Roadmap

### ISSUE THREAD

**Issue by MrSaints** [MrSaints/historyx#1]
~~The current version is v1.0.0, although in reality I'd consider it v0.0.0. This thread will cover the _"essentials"_ that needs to be done before a proper release (i.e. app store) can be made.~~

~~On a slightly related note, I'm planning on switching away from MDL entirely. It's a great framework, but it's built with too much reliance on its JS libraries (with a bunch of listeners)~~
## 

~~I've decided to redo the entire extension, starting with a new CSS framework. It's most likely going to be Bootstrap 4 (Alpha). Rationale is simple: it's widely used, and its new version is fairly lightweight. It works without JS, and it feels a lot more predictable than MDL.~~

~~v2.0.0 is committed. Refactored, and reorganised the entire app. It's now using [Bootstrap 4 (Alpha)](v4-alpha.getbootstrap.com/getting-started/introduction/). Components, actions, stores, and constants are further compartmentalised, and cleaned up.~~

---

This is the roadmap for the next _major_ release v3.0.0.
## Scenarios
- **Date specific (default):-**  "DD/MM/YY" | Time
- **Query specific:-** "Searching: X" | Time and date (same for _stale visits_)
- **Query, and date specific:-** "Searching: X on DD/MM/YY" | Time
## Completed
- [x] Pagination (???) / Show X results (e.g. All);
- [x] Search ALL (i.e. not date specific - how to best handle this?).
## To be added

A separate webpack config should be created for the development environment. The extension also needs an automatic packager / builder (e.g. gulp).
- [ ] Settings page: alter date format;
- [x] Deleting single URL;
- [ ] Deleting ALL / selected;
- [ ] Undo delete (recycle bin?);
- [ ] Sorting (e.g. by date, and alphabetical order)
- [ ] Grouping (e.g. by hostname);
- [ ] Tagging (i.e. custom search);
- [ ] Reset;
- [ ] About / metainfo page (e.g. version);
- [x] Show full URL.
## Under consideration
- [ ] [omnibox](https://developer.chrome.com/extensions/omnibox#type-SuggestResult)
- [ ] Most visited (by date? should this be on a separate page?) | Could use [topSites API](https://developer.chrome.com/extensions/topSites);
- [ ] Statistics or something fancy... _(see above)_
- [ ] Routing (???);
- [ ] Custom calendar element (I don't like the current one);
- [ ] Star on bookmarks;
- [ ] Autoreload.
## Issues
- [ ] Retrieving real dates / times (for stale links);
- [x] Fix pagination when "ALL" limit is used;
- [ ] Button to refresh stale results (possibly the title);
- [ ] Reduce font-size?

Perhaps we should use Immutable.js...

**Comment by MrSaints** [comment]
![2016-01-03-014828_3286x1080_scrot](https://cloud.githubusercontent.com/assets/68859/12076951/57fb38f6-b1bc-11e5-8cc3-e36bfe3d076a.png)

Started work on v3.0.0. New design.

**Comment by MrSaints** [comment]
I got bored, and rewrote it, again: https://github.com/MrSaints/historyx/tree/v3

![chrome-extension___lnbocnimmniifabkofgadjjikegejgeh_build_index html laptop with hidpi screen](https://user-images.githubusercontent.com/68859/36062813-a439fd8e-0e6b-11e8-9e3e-9a2aee086b11.png)

**Comment by MrSaints** [comment]
Moving some of the issues to a v3 project.
